name: Compliance Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * 1-5"

jobs:
  CyDig-Compliance-Workflow:
    uses: 11934FD6-27F9-4A3C-9396-2A5CB76457AF/opera-compliance/.github/workflows/compliance-template.yml@main # Path to where your compliance-template is located.
    secrets: inherit
    with:
      appRegNumber: 2